[package]
name = "RIP-seminar"
version = "0.1"
lean_version = "nightly-2018-08-23"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "4fc67f8f219d4de0680113fb8f6ee2a860b3aa79"}
